on:
  push:
    branches:
      - "develop"
      - "staging"
      - "master"

env:
  GO_VERSION: "1.16"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Pull dependencies"
        run: go mod vendor
      - name: "Unit tests"
        run: make test
      - name: "Linter"
        run: make lint
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Calculate semver tag"
        id: semver-tag
        uses: gandarez/semver-action@3-branches
        with:
          debug: true
      - name: "Create tag"
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.semver-tag.outputs.semver_tag }}",
              sha: context.sha
            })
      - name: Changelog
        uses: gandarez/changelog-action@v1.0.2
        id: changelog
        with:
          exclude: |
            ^Merge pull request .*
          debug: true
      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.semver-tag.outputs.semver_tag }}
          tag_name: ${{ steps.semver-tag.outputs.semver_tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.semver-tag.outputs.is_prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

